{{- if .Values.sync_secrets.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "application.name" $ }}-sync-secrets
  namespace: argocd
  {{- if .Values.sync_secrets.annotations }}
  annotations:
{{ toYaml .Values.sync_secrets.annotations | indent 4 }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: sync-secrets
      containers:
      - name: sync-secrets
        image: {{ .Values.sync_secrets.image.repository }}:{{ .Values.sync_secrets.image.tag }}
        args: []
        env:
        - name: SERVICE
          value: {{ template "application.name" . }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        - name: BRANCH
          value: "develop"
        {{- if .Values.sync_secrets.envFrom }}
        envFrom:
        {{- range .Values.sync_secrets.envFrom }}
        {{- if (eq .type "configmap") }}
        - configMapRef:
            {{- if .name }}
            name: {{ .name }}
            {{- else }}
            name: {{ template "application.name" $ }}
            {{- end }}
        {{- end }}
        {{- if (eq .type "secret") }}
        - secretRef:
            {{- if .name }}
            name: {{ .name }}
            {{- else }}
            name: {{ template "application.name" $ }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 2

{{- end }}
